[package]
name = "unitypkg-core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
flate2 = "1.0.30"
regex = "1.10.5"
tar = "0.4.41"
uuid = { version = "1.9.1", features = ["v4"] }
